server:
  port: 8080
spring:
  application:
    name: household-budget-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123321
    jpa:
      open-in-view: on
      hibernate:
        ddl-auto: validate
      show-sql: true
